linters-settings:
  gofmt:
    simplify: false

linters:
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - exportloopref
    - asciicheck
    - depguard
    - godot
    - gomodguard
    - goprintffuncname
    - nolintlint
    - rowserrcheck

issues:
  exclude:
    - G307 # gosec
