linters-settings:
  gofmt:
    simplify: false

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - gochecknoglobals
    - interfacer
    - lll
    - scopelint
    - maligned
    - gocyclo
    - funlen
    - godox
