stack: Go 1.12
clone_folder: c:\gopath\src\github.com\ktr0731\evans
cache:
  - vendor -> go.mod
install:
  - set GO111MODULE=on
  - rm -rf go.sum # TODO: remove this line if AppVeyor supports Go v1.11.5 or later.
  - go mod download
  - go mod verify
build: off
test_script:
  - set CGO_ENABLED=0
  - set GO111MODULE=on
  - go build
  - go test -tags e2e -v ./...
