stack: Go 1.11
clone_folder: c:\gopath\src\github.com\ktr0731\evans
cache:
  - vendor -> go.mod
install:
  - set GO111MODULE=on
  - go mod download
  - go mod verify
build: off
test_script:
  - set CGO_ENABLED=0
  - set GO111MODULE=on
  - go build
  - go test -tags e2e -v ./...
