clone_folder: c:\gopath\src\github.com\ktr0731\evans
environment:
  GOPATH: c:\gopath
  PATH: '%GOPATH%\bin;%PATH%'
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
build: off
test_script:
  - go build
  - go test -tags e2e -race $(go list ./...)
