// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repl

import (
	"github.com/ktr0731/evans/grpc"
	"github.com/ktr0731/evans/idl"
	"sync"
)

var (
	lockSpecMockPackageNames   sync.RWMutex
	lockSpecMockRPC            sync.RWMutex
	lockSpecMockRPCs           sync.RWMutex
	lockSpecMockServiceNames   sync.RWMutex
	lockSpecMockTypeDescriptor sync.RWMutex
)

// Ensure, that SpecMock does implement idl.Spec.
// If this is not the case, regenerate this file with moq.
var _ idl.Spec = &SpecMock{}

// SpecMock is a mock implementation of idl.Spec.
//
//     func TestSomethingThatUsesSpec(t *testing.T) {
//
//         // make and configure a mocked idl.Spec
//         mockedSpec := &SpecMock{
//             PackageNamesFunc: func() []string {
// 	               panic("mock out the PackageNames method")
//             },
//             RPCFunc: func(svcName string, rpcName string) (*grpc.RPC, error) {
// 	               panic("mock out the RPC method")
//             },
//             RPCsFunc: func(svcName string) ([]*grpc.RPC, error) {
// 	               panic("mock out the RPCs method")
//             },
//             ServiceNamesFunc: func() []string {
// 	               panic("mock out the ServiceNames method")
//             },
//             TypeDescriptorFunc: func(msgName string) (interface{}, error) {
// 	               panic("mock out the TypeDescriptor method")
//             },
//         }
//
//         // use mockedSpec in code that requires idl.Spec
//         // and then make assertions.
//
//     }
type SpecMock struct {
	// PackageNamesFunc mocks the PackageNames method.
	PackageNamesFunc func() []string

	// RPCFunc mocks the RPC method.
	RPCFunc func(svcName string, rpcName string) (*grpc.RPC, error)

	// RPCsFunc mocks the RPCs method.
	RPCsFunc func(svcName string) ([]*grpc.RPC, error)

	// ServiceNamesFunc mocks the ServiceNames method.
	ServiceNamesFunc func() []string

	// TypeDescriptorFunc mocks the TypeDescriptor method.
	TypeDescriptorFunc func(msgName string) (interface{}, error)

	// calls tracks calls to the methods.
	calls struct {
		// PackageNames holds details about calls to the PackageNames method.
		PackageNames []struct {
		}
		// RPC holds details about calls to the RPC method.
		RPC []struct {
			// SvcName is the svcName argument value.
			SvcName string
			// RpcName is the rpcName argument value.
			RpcName string
		}
		// RPCs holds details about calls to the RPCs method.
		RPCs []struct {
			// SvcName is the svcName argument value.
			SvcName string
		}
		// ServiceNames holds details about calls to the ServiceNames method.
		ServiceNames []struct {
		}
		// TypeDescriptor holds details about calls to the TypeDescriptor method.
		TypeDescriptor []struct {
			// MsgName is the msgName argument value.
			MsgName string
		}
	}
}

// PackageNames calls PackageNamesFunc.
func (mock *SpecMock) PackageNames() []string {
	if mock.PackageNamesFunc == nil {
		panic("SpecMock.PackageNamesFunc: method is nil but Spec.PackageNames was just called")
	}
	callInfo := struct {
	}{}
	lockSpecMockPackageNames.Lock()
	mock.calls.PackageNames = append(mock.calls.PackageNames, callInfo)
	lockSpecMockPackageNames.Unlock()
	return mock.PackageNamesFunc()
}

// PackageNamesCalls gets all the calls that were made to PackageNames.
// Check the length with:
//     len(mockedSpec.PackageNamesCalls())
func (mock *SpecMock) PackageNamesCalls() []struct {
} {
	var calls []struct {
	}
	lockSpecMockPackageNames.RLock()
	calls = mock.calls.PackageNames
	lockSpecMockPackageNames.RUnlock()
	return calls
}

// RPC calls RPCFunc.
func (mock *SpecMock) RPC(svcName string, rpcName string) (*grpc.RPC, error) {
	if mock.RPCFunc == nil {
		panic("SpecMock.RPCFunc: method is nil but Spec.RPC was just called")
	}
	callInfo := struct {
		SvcName string
		RpcName string
	}{
		SvcName: svcName,
		RpcName: rpcName,
	}
	lockSpecMockRPC.Lock()
	mock.calls.RPC = append(mock.calls.RPC, callInfo)
	lockSpecMockRPC.Unlock()
	return mock.RPCFunc(svcName, rpcName)
}

// RPCCalls gets all the calls that were made to RPC.
// Check the length with:
//     len(mockedSpec.RPCCalls())
func (mock *SpecMock) RPCCalls() []struct {
	SvcName string
	RpcName string
} {
	var calls []struct {
		SvcName string
		RpcName string
	}
	lockSpecMockRPC.RLock()
	calls = mock.calls.RPC
	lockSpecMockRPC.RUnlock()
	return calls
}

// RPCs calls RPCsFunc.
func (mock *SpecMock) RPCs(svcName string) ([]*grpc.RPC, error) {
	if mock.RPCsFunc == nil {
		panic("SpecMock.RPCsFunc: method is nil but Spec.RPCs was just called")
	}
	callInfo := struct {
		SvcName string
	}{
		SvcName: svcName,
	}
	lockSpecMockRPCs.Lock()
	mock.calls.RPCs = append(mock.calls.RPCs, callInfo)
	lockSpecMockRPCs.Unlock()
	return mock.RPCsFunc(svcName)
}

// RPCsCalls gets all the calls that were made to RPCs.
// Check the length with:
//     len(mockedSpec.RPCsCalls())
func (mock *SpecMock) RPCsCalls() []struct {
	SvcName string
} {
	var calls []struct {
		SvcName string
	}
	lockSpecMockRPCs.RLock()
	calls = mock.calls.RPCs
	lockSpecMockRPCs.RUnlock()
	return calls
}

// ServiceNames calls ServiceNamesFunc.
func (mock *SpecMock) ServiceNames() []string {
	if mock.ServiceNamesFunc == nil {
		panic("SpecMock.ServiceNamesFunc: method is nil but Spec.ServiceNames was just called")
	}
	callInfo := struct {
	}{}
	lockSpecMockServiceNames.Lock()
	mock.calls.ServiceNames = append(mock.calls.ServiceNames, callInfo)
	lockSpecMockServiceNames.Unlock()
	return mock.ServiceNamesFunc()
}

// ServiceNamesCalls gets all the calls that were made to ServiceNames.
// Check the length with:
//     len(mockedSpec.ServiceNamesCalls())
func (mock *SpecMock) ServiceNamesCalls() []struct {
} {
	var calls []struct {
	}
	lockSpecMockServiceNames.RLock()
	calls = mock.calls.ServiceNames
	lockSpecMockServiceNames.RUnlock()
	return calls
}

// TypeDescriptor calls TypeDescriptorFunc.
func (mock *SpecMock) TypeDescriptor(msgName string) (interface{}, error) {
	if mock.TypeDescriptorFunc == nil {
		panic("SpecMock.TypeDescriptorFunc: method is nil but Spec.TypeDescriptor was just called")
	}
	callInfo := struct {
		MsgName string
	}{
		MsgName: msgName,
	}
	lockSpecMockTypeDescriptor.Lock()
	mock.calls.TypeDescriptor = append(mock.calls.TypeDescriptor, callInfo)
	lockSpecMockTypeDescriptor.Unlock()
	return mock.TypeDescriptorFunc(msgName)
}

// TypeDescriptorCalls gets all the calls that were made to TypeDescriptor.
// Check the length with:
//     len(mockedSpec.TypeDescriptorCalls())
func (mock *SpecMock) TypeDescriptorCalls() []struct {
	MsgName string
} {
	var calls []struct {
		MsgName string
	}
	lockSpecMockTypeDescriptor.RLock()
	calls = mock.calls.TypeDescriptor
	lockSpecMockTypeDescriptor.RUnlock()
	return calls
}
