// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/ktr0731/evans/config"
	"github.com/ktr0731/evans/usecase"
)

// Injectors from injector.go:

func initializeCLIParams(cfg *config.Config, in JSONReader) (*usecase.InteractorParams, error) {
	environment, err := provideEnv(cfg)
	if err != nil {
		return nil, err
	}
	jsonPresenter := provideJSONPresenter()
	gatewayJSONFileInputter := provideJSONInputter(in)
	gatewayDynamicBuilder := provideDynamicBuilder()
	grpcClient, err := provideGRPCClient(cfg, gatewayDynamicBuilder)
	if err != nil {
		return nil, err
	}
	interactorParams := &usecase.InteractorParams{
		Env:            environment,
		OutputPort:     jsonPresenter,
		InputterPort:   gatewayJSONFileInputter,
		DynamicBuilder: gatewayDynamicBuilder,
		GRPCClient:     grpcClient,
	}
	return interactorParams, nil
}
