name: "Auto approve Pull Requests and enable auto-merge"
on:
  pull_request_target
permissions:
  pull-requests: write
jobs:
  worker:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.4.0
        with:
          github-token: ${{secrets.GH_TOKEN}}
      - name: Approve
        run: gh pr review --approve $PR_URL
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      - name: Enable auto-merge
        run: gh pr merge --auto --squash $PR_URL
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
